[package]
name = "resistor"
version = "0.1.0"
edition = "2021"
description = "Программа для вычисления сопротивления резисторов по цветам"
authors = ["{Tsar} <michail383krasnov@mail.ru>"]
license = "GPL-3.0-or-later"

[profile.release]
lto = true
strip = true
debug = false
panic = 'abort'
opt-level = 's'

[[bin]]
name = "resistor_cli"

[[bin]]
name = "resistor_gui"

[dependencies]
cursive = "0.20.0"
libmsg = { git = "https://gitlab.com/calmiralinux/libmsg" }
gtk = { version = "0.7.2", package = "gtk4", features = ["v4_8"] }
